### PR TITLE
Add jdk 10 & 11 to Travis build

### PR DESCRIPTION
**Pull request by marcospereira**
Checking if https://github.com/travis-ci/travis-build/pull/1347 is already available to all repositories. :-)

### CODE REVIEW

**Comment by sormuras** [comment]
...should work. 🤞

**Comment by sormuras** [comment]
The JDKs were installed correctly. ✔️ 

Now there are some modular world issues...  :-)

**Comment by wsargent** [comment]
> Now there are some modular world issues... :-)

Have you tried turning it off and on again?

**Comment by sormuras** [comment]
> Have you tried turning it off and on again?

~~Huh?~~ Okay, it took some time. 😃 

Looks like `sbt` doesn't like JDK 10 or 11. Same goes for Gradle and JDK 11.

For example: https://travis-ci.org/playframework/play-scala-starter-example/jobs/385785029#L1002

`javax.xml.bind.DatatypeConverter` is missing. Smells like some "--add-modules" love is needed.

**Comment by mkurz** [comment]
sbt 1.1.6 ist tagged already

**Comment by marcospereira** [comment]
Looks like Gradle is getting there: https://github.com/gradle/gradle/issues/4515

> javax.xml.bind.DatatypeConverter is missing. Smells like some "--add-modules" love is needed.

Yeah, the last commit here should fix this.

**Comment by marcospereira** [comment]
> sbt 1.1.6 ist tagged already

Add a new commit to use it.

**Comment by marcospereira** [comment]
> Same goes for Gradle and JDK 11.

Update to Gradle 4.7 which I think contains a fix for this. :-)

**Comment by sormuras** [comment]
Gradle 4.7 fixed Java 10 issue. Gradle 4.8 tackles Java 11 ones. Try 4.8-rc-2 (or -3)

**Comment by marcospereira** [comment]
The last commit should make the build pass:

https://github.com/playframework/play-scala-starter-example/pull/86/commits/9c249a296be002492e9048f0216f4fc8dc0f35d0

/cc @schmitch ☝️

**Pull request merged**
