### PR TITLE
Change user action from clicking to refreshing

### PR DESCRIPTION
**Pull request by AlbaroPereyra**
There is no button to click and the webpage currently suggests to click. The only way to make the counter count is by refreshing the page.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @AlbaroPereyra,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by AlbaroPereyra** [comment]
I signed the CLA.

**Comment by octonato** [comment]
CLA signed, but check didn't capture it.
https://www.lightbend.com/contribute/cla/check/AlbaroPereyra

**Comment by marcospereira** [comment]
Closing and re-opening to see if the CLA bot will work as expected.

**Review by octonato — APPROVED** [review]

**Pull request merged**
